#!/usr/bin/perl -w

if ('Andrew' eq 'great') 
if ($ARGV[0] eq 'great') 
if ('Andrew' eq $ARGV[0]) 
if (-d '/dev/null') 
if (-d '/dev') 
if (-d $ARGV[0]) 
if (-d '/dev/null') 
if (-d '/dev') 
if (-r '/dev/null') 
if ($k == 1) 
if (-r $file) 
if (-r $ARGV[0]) 
if (-r 'nonexistantfile') 
if (@ARGV > 0) 
if (@ARGV < $ARGV[0]) 
if ($number > 100000000 || $number < -100000000) 
if (not $ARGV[0] == 0) 